step_3_reasoning = {'layer1' :'''Reasoning Layer 1: while dogs generally look similar when wanting to classify breeds we want to identify patterns these patterns could be spots on fur (such as spots on dalmatians, or the curls of a poodle), hence adding a layer of filters allows us to build an object capable of detecting spatial patterns anywhere across the image. By choosing 16 different filters we give the possibility of this layer developing to detect 16 different patterns the combination could provide useful in determining a breed. 

                    By choosing a kernel size of 4 we allow for a 16 pixels pattern grid which should be large enough to detect most geometric patterns such as spots or curls. 

                    I chose padding same to avoid issues where filter values are untrained due to a lack of data when meeting the boundary of an image.
                    
                    Finally, relu activation helps control the issue of vanishing gradient which given the number of parameters at play in a CNN can cause issues with training which may appear with more primitive activation functions such as a sigmoid.''',
                   'layer2' : """Reasoning Layer 2: convolutional filters are useful however without spiralling parameter size we cannot follow up with additional convolutional layers unless we provide a 'reconvoluted' layer such as a pooling layer which diminishes the dimensionality of our convolution back to an array of a similar (though reduce in size) of our original input. 
                   
                    This allows us to then pick up additional salient features in identified in the filters by taking the max filter value in different regions to represent that region, essentially scaling down and reconvoluting our filters without losing spatial information. I set pooling size to 2 to control my number of parameters.
                    """,
                   'layer3': '''Similarly for layer1 filters are useful to spot patterns, sometimes these patterns can be more abstract and reflect a pattern of patterns. In this case the input of our convolutional layer is already a max pooling of convolutional filters and hence we are performing a reconvolution on the filters themselves. If we imagine say one filter picks up spots and others pick up stripes, after max pooling we can convolute the outputs to identify patterns across filters and this is useful when identifying breeds as in many cases it is patterns of patterns that determine a breed. That is to say many dogs may share 4 given patterns but they may not share the combination of these etc. In order to build more sensitivity to this I used 32 filters as suggested and kept the kernel smaller than before to control parameter size.
                   ''',
                   'layer4': '''Again, if we want to avoid spiralling parameters we can apply max pooling to downscale our filters while maintaining spatial informations to provide the input to a new convolutional layer, that is what I have done, I have kept a small max pooling size to control parameters as this model is slow to train''',
                   'layer5': '''Once more I add more convolutional filters to detect patterns in the third order (patterns of patterns of patterns). Increasing the size helps us give more variable paths to the final output layer which is useful when dealing with a high cardinality classification problem such as this dog breed classification problem''',
                   'layer6': '''To reduce dimensionality before going to a global pooling layer, which is a needed step to output to a dense layer, I have applied max pooling with a pool size fo 2 to control parameter size.''',
                    'layer7' : '''To deconvolute our convolutional nodes we need to apply some global aggregation which brings our high dimensional layers back to a simple MLP layer, global pooling is an inexpensive way to do this while allowing a free-association of the input layers (through interaction in the averaging), and it feeds well into the prediction (dense layer) which follows'''
}